apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  strategy:
    rollingUpdate: # Rampted Slow Rollout
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 074017796595.dkr.ecr.ap-northeast-2.amazonaws.com/flask-app:1.0
        ports:
          - containerPort: 8080
        readinessProbe:
          periodSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          periodSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        resources:
          requests:
            cpu: "30mi"
            memory: "50Mi"
          limits:
            cpu: "30mi"
            memory: "50Mi"
        imagePullPolicy: Always